export default {
    state: {
      cars: [
                // Panamera II Turbo S E - Hybrid
                {
                    id: 1,
                    img1: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-1.jpg'),
                    img2: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-2.jpg'),
                    img3: require('@/assets/porsche-panamera/int/porsche-panamera-int-1.jpg'),
                    marke: 'Porsche',
                    model: 'Panamera II Turbo S E-Hybrid',
                    price: 150000,
                    year: 2021,
                    bodyType: 'sedan',
                    transmission: 'automatic',
              kilometres: 17000,
              photo: [
                  { img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-1.jpg'), img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-1.jpg'), },
                  {img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-2.jpg'),img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-2.jpg'),},
                  {img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-3.jpg'),img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-3.jpg'),},
                  {img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-4.jpg'),img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-4.jpg'),},
                  {img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-5.jpg'),img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-5.jpg'),},
                  {img: require('@/assets/porsche-panamera/ext/porsche-panamera-ext-6.jpg'),img1: require('@/assets/porsche-panamera/int/porsche-panamera-int-6.jpg'),},  
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '8 cylinders',
                        fuelConsumption: '2.7L per 100 km.',
                        topSpeed: 'Max speed 315 km/h',
                        horsePower: '690 HP',
                        acceleration: '0-100 in 3.2 s.',
                        powerSteering: 'Power steering',
                        rpm: '2100 - 5750 rpm'
                    },
                    description: 'This engine produces a maximum power of 571 PS (563 bhp - 420 kW) at 5750 rpm and a maximum torque of 770 Nm (567 lb.ft) at 2100 rpm. The power is transmitted to the road by the all wheel drive (AWD) with a 8 speed Dualclutch Automatic gearbox.On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Panamera 2021 has Independent Double Wishbones.Air Suspension.Anti - roll bar.front suspension and Multilink.Air Suspension.Anti - roll bar.rear suspension.Stock tire sizes are 275 / 35 on 21 inch rims at the front, and 315 / 30 on 21 inch rims at the rear.For stopping power, the Panamera 2021 Turbo S E- Hybrid braking system includes Vented Discs at the front and Vented Discs at the rear. The Panamera 2021 model is a sedan car manufactured by Porsche, with 5 doors and 4 seats, sold new from year 2021.',

                },
                // Outlander
                {
                    id: 2,
                    img1: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-1.jpg'),
                    img2: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-2.jpg'),
                    img3: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-1.jpg'),
                    marke: 'Mitsubishi',
                    model: 'Outlander ',
                    price: 35000,
                    year: 2016,
                    bodyType: 'suv',
                    transmission: 'manual',
                    kilometres: 65000,
                    photo: [
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-1.jpg'), img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-1.jpg'),},
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-2.jpg'),img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-2.jpg'),},
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-3.jpg'),img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-3.jpg'),},
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-4.jpg'),img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-4.jpg'),},
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-5.jpg'),img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-5.jpg'),},
                        {img: require('@/assets/mitsubishi-outlander/ext/mitsubishi-outlander-ext-6.jpg'),img1: require('@/assets/mitsubishi-outlander/int/mitsubishi-outlander-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Front wheel drive',
                        cylindersQuantity: '4 cylinders',
                        fuelConsumption: '6.2L per 100 km.',
                        topSpeed: 'Max speed 192 km/h',
                        horsePower: '148 HP',
                        acceleration: '0-100 in 11.5 s.',
                        powerSteering: 'Power steering',
                        rpm: '1500 - 6000 rpm'
                    },
                    description: 'On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Outlander 3 (2015 Facelift) has McPherson struts. Coil springs. front suspension and Coil springs. rear suspension. Stock tire sizes are 225 / 55 on 18 inch rims at the front, and 225 / 55 on 18 inch rims at the rear. For stopping power, the Outlander 3 (2015 Facelift) 200 MPI HPT 2WD 5 seats braking system includes Vented Discs at the front and Discs at the rear. The Outlander 3(2015 Facelift) model is a TT car manufactured by Mitsubishi, with 5 doors and 5 seats, sold new from year 2016 until 2018, and available after that as a used car.',
                },
                // AMG GT Black Series
                {
                    id: 3,
                    img1: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-1.jpg'),
                    img2: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-2.jpg'),
                    img3: require('@/assets/mercedes-amg/int/mercedes-amg-int-1.jpg'),
                    marke: 'Mercedes-Benz',
                    model: 'AMG GT Black Series',
                    price: 90000,
                    year: 2021,
                    bodyType: 'coupe',
                    transmission: 'manual',
                    kilometres: 7000,
                    photo: [
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-1.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-1.jpg'),},
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-2.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-2.jpg'),},
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-3.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-3.jpg'),},
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-4.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-4.jpg'),},
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-5.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-5.jpg'),},
                        {img: require('@/assets/mercedes-amg/ext/mercedes-amg-ext-6.jpg'),img1: require('@/assets/mercedes-amg/int/mercedes-amg-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Rear wheel drive',
                        cylindersQuantity: '8 cylinders',
                        fuelConsumption: '12.7L per 100 km.',
                        topSpeed: 'Max speed 310 km/h',
                        horsePower: '523 HP',
                        acceleration: '0-100 in 3.8 s.',
                        powerSteering: 'Power steering',
                        rpm: '2100 - 6750 rpm',
                    },
                    description: 'This engine produces a maximum power of 530 PS (523 bhp - 390 kW) at 5500-6750 rpm and a maximum torque of 670 Nm (494 lb.ft) at 2100-5250 rpm. The power is transmitted to the road by the rear wheel drive (RWD) with a 7 speed Automatic gearbox.On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the AMG GT Roadster has Independent Double Wishbones.Coil Springs.Anti - roll bar.front suspension and Independent Double Wishbones.Coil Springs.Anti - roll bar.rear suspension.Stock tire sizes are 255 / 35 on 19 inch rims at the front, and 295 / 35 on 19 inch rims at the rear.For stopping power, the AMG GT Roadster braking system includes Vented Discs at the front and Vented Discs at the rear.The AMG GT Roadster model is a Cabrio car manufactured by Mercedes Benz, with 2 doors and 2 seats, sold new from year 2021.',
                },
                // W124 420
                {
                    id: 4,
                    img1: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-1.jpg'),
                    img2: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-2.jpg'),
                    img3: require('@/assets/mercedes-w124/int/mercedes-w124-int-1.jpg'),
                    marke: 'Mercedes-Benz',
                    model: 'W124 420',
                    price: 13200,
                    year: 1993,
                    bodyType: 'sedan',
                    transmission: 'manual',
                    kilometres: 195000,
                    photo: [
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-1.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-1.jpg'),},
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-2.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-2.jpg'),},
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-3.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-3.jpg'),},
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-4.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-4.jpg'),},
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-5.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-5.jpg'),},
                        {img: require('@/assets/mercedes-w124/ext/mercedes-w124-ext-6.jpg'),img1: require('@/assets/mercedes-w124/int/mercedes-w124-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Front wheel drive',
                        cylindersQuantity: '8 cylinders',
                        fuelConsumption: '11.7L per 100 km.',
                        topSpeed: 'Max speed 250 km/h',
                        horsePower: '286 HP',
                        acceleration: '0-100 in 7.2 s.',
                        powerSteering: 'Power steering',
                        rpm: '2100 - 5700 rpm',
                    },
                    description: 'This engine produces a maximum power of 279 PS (275 bhp - 205 kW) at 5700 rpm and a maximum torque of 400 Nm (295 lb.ft) at 3900 rpm. The power is transmitted to the road by the rear wheel drive (RWD) with a 4 speed Automatic gearbox.On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the W124 Sedan has Independent; anti- roll bar front suspension and Multilink with anti - roll bar rear suspension.Stock tire sizes are 195 / 65 on 15 inch rims at the front, and 195 / 65 on 15 inch rims at the rear.For stopping power, the W124 Sedan E 420 braking system includes VentedDiscs at the front and Discs at the rear.The W124 Sedan model is a car manufactured by Mercedes Benz, with 4 doors and 5 seats, sold new from year 1993 until 1995, and available after that as a used car.',
                },
                // C - Class All - Terrain
                {
                    id: 5,
                    img1: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-1.jpg'),
                    img2: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-2.jpg'),
                    img3: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-1.jpg'),
                    marke: 'Mercedes-Benz',
                    model: 'C-Class All-Terrain ',
                    price: 67000,
                    year: 2022,
                    bodyType: 'sedan',
                    transmission: 'automatic',
                    kilometres: 10000,
                    photo: [
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-1.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-1.jpg'),},
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-2.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-2.jpg'),},
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-3.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-3.jpg'),},
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-4.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-4.jpg'),},
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-5.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-5.jpg'),},
                        {img: require('@/assets/mercedes-c-class/ext/mercedes-c-class-ext-6.jpg'),img1: require('@/assets/mercedes-c-class/int/mercedes-c-class-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '4 cylinders',
                        fuelConsumption: '6.9L per 100 km.',
                        topSpeed: 'Max speed 231 km/h',
                        horsePower: '201 HP',
                        acceleration: '0-100 in 7.5 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5800 rpm',
                    },
                    description: 'This engine produces a maximum power of 204 PS (201 bhp - 150 kW) at 5800 rpm and a maximum torque of 300 Nm (221 lb.ft) at 1800 rpm. The power is transmitted to the road by the all wheel drive (AWD) with a 9 speed Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Class C All- Terrain(S206) has Independent McPherson.Coil Springs.Anti - roll bar.front suspension and Multilink.Coil Springs.Anti - roll bar.rear suspension.Stock tire sizes are 225 / 55 on 17 inch rims at the front, and 225 / 55 on 17 inch rims at the rear.For stopping power, the Class C All - Terrain(S206) 200 4MATIC braking system includes Vented Discs at the front and Vented Discs at the rear. The Class C All - Terrain(S206) model is a Estate car manufactured by Mercedes Benz, with 5 doors and 5 seats, sold new from year 2022.',
                },
                // Audi A7
                {
                    id: 6,
                    img1: require('@/assets/audi-a7/ext/audi-a7-ext-1.jpg'),
                    img2: require('@/assets/audi-a7/ext/audi-a7-ext-2.jpg'),
                    img3: require('@/assets/audi-a7/int/audi-a7-int-1.jpg'),
                    marke: 'Audi',
                    model: 'A7 I (4G) S-tronic',
                    price: 56500,
                    year: 2020,
                    bodyType: 'sedan',
                    transmission: 'automatic',
                    kilometres: 93000,
                    photo: [
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-1.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-1.jpg'),},
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-2.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-2.jpg'),},
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-3.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-3.jpg'),},
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-4.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-4.jpg'),},
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-5.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-5.jpg'),},
                        {img: require('@/assets/audi-a7/ext/audi-a7-ext-6.jpg'),img1: require('@/assets/audi-a7/int/audi-a7-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Front wheel drive',
                        cylindersQuantity: '4 cylinders',
                        fuelConsumption: '6.2L per 100 km.',
                        topSpeed: 'Max speed 250 km/h',
                        horsePower: '261 HP',
                        acceleration: '0-100 in 6.9 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5800 rpm',
                    },
                    description: 'This engine produces a maximum power of 265 PS (261 bhp - 195 kW) at 5000 rpm and a maximum torque of 370 Nm (272 lb.ft) at 1600 rpm. The power is transmitted to the road by the front wheel drive (FWD) with a 7 speed Dualclutch Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the A7 Sportback(C8) has Multilink.Coil Springs.Anti - roll bar.front suspension and Multilink.Coil Springs.Anti - roll bar.rear suspension.Stock tire sizes are 255 / 55 on 18 inch rims at the front, and 255 / 55 on 18 inch rims at the rear.For stopping power, the A7 Sportback(C8) 45 TFSI braking system includes Vented Discs at the front and Vented Discs at the rear. The A7 Sportback(C8) model is a Hatchback car manufactured by Audi, with 5 doors and 4 seats, sold new from year 2020.',
                },
                // Audi A6
                {
                    id: 7,
                    img1: require('@/assets/audi-a6/ext/audi-a6-ext-1.jpg'),
                    img2: require('@/assets/audi-a6/ext/audi-a6-ext-2.jpg'),
                    img3: require('@/assets/audi-a6/int/audi-a6-int-1.jpg'),
                    marke: 'Audi',
                    model: 'A6 Avant sport 40TDI ',
                    price: 39000,
                    year: 2019,
                    bodyType: 'sedan',
                    transmission: 'automatic',
                    kilometres: 92000,
                    photo: [
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-1.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-1.jpg'),},
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-2.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-2.jpg'),},
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-3.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-3.jpg'),},
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-4.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-4.jpg'),},
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-5.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-5.jpg'),},
                        {img: require('@/assets/audi-a6/ext/audi-a6-ext-6.jpg'),img1: require('@/assets/audi-a6/int/audi-a6-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Front wheel drive',
                        cylindersQuantity: '4 cylinders',
                        fuelConsumption: '6.2L per 100 km.',
                        topSpeed: 'Max speed 250 km/h',
                        horsePower: '242 HP',
                        acceleration: '0-100 in 7.0 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5800 rpm',
                    },
                    description: 'This engine produces a maximum power of 245 PS (242 bhp - 180 kW) at 5000 rpm and a maximum torque of 370 Nm (272 lb.ft) at 1600 rpm. The power is transmitted to the road by the front wheel drive (FWD) with a 7 speed Dualclutch Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the A6(C8) Avant has Multilink.Coil Springs.Anti - roll bar.front suspension and Multilink.Coil Springs.Anti - roll bar.rear suspension.Stock tire sizes are 255 / 55 on 18 inch rims at the front, and 255 / 55 on 18 inch rims at the rear.For stopping power, the A6(C8) Avant 45 TFSI braking system includes Vented Discs at the front and Vented Discs at the rear. The A6(C8) Avant model is a Estate car manufactured by Audi, with 5 doors and 5 seats, sold new from year 2019.',
                },
                // F - 150 RAPTOR
                {
                    id: 8,
                    img1: require('@/assets/ford-f150/ext/ford-f150-ext-1.jpg'),
                    img2: require('@/assets/ford-f150/ext/ford-f150-ext-2.jpg'),
                    img3: require('@/assets/ford-f150/int/ford-f150-int-1.jpg'),
                    marke: 'Ford',
                    model: 'F-150 RAPTOR',
                    price: 75000,
                    year: 2018,
                    bodyType: 'truck',
                    transmission: 'automatic',
                    kilometres: 40000,
                    photo: [
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-1.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-1.jpg'),},
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-2.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-2.jpg'),},
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-3.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-3.jpg'),},
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-4.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-4.jpg'),},
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-5.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-5.jpg'),},
                        {img: require('@/assets/ford-f150/ext/ford-f150-ext-6.jpg'),img1: require('@/assets/ford-f150/int/ford-f150-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Rear wheel drive',
                        cylindersQuantity: '8 cylinders',
                        fuelConsumption: '13.1L per 100 km.',
                        topSpeed: 'Max speed 220 km/h',
                        horsePower: '385 HP',
                        acceleration: '0-100 in 13.0 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5750 rpm',
                    },
                    description: 'This engine produces a maximum power of 390 PS (385 bhp - 287 kW) at 5750 rpm and a maximum torque of 525 Nm (387 lb.ft) at 3850 rpm. The power is transmitted to the road by the rear wheel drive (RWD) with a 6 speed Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the F- 150 has Coil - on - shock front suspension and Hotchkiss - type rear suspension.For stopping power, the F - 150 5.0L V8 4x2 8 ft.Regular braking system includes Vented Discs at the front and Vented Discs at the rear. The F - 150 model is a Pick Up car manufactured by Ford, with 2 doors and 3 seats, sold new from year 2018.',
                },
                // Sedona LX
                {
                    id: 9,
                    img1: require('@/assets/kia-sedona/ext/kia-sedona-ext-1.jpg'),
                    img2: require('@/assets/kia-sedona/ext/kia-sedona-ext-2.jpg'),
                    img3: require('@/assets/kia-sedona/int/kia-sedona-int-1.jpg'),
                    marke: 'Kia',
                    model: 'Sedona LX',
                    price: 22000,
                    year: 2017,
                    bodyType: 'van',
                    transmission: 'manual',
                    kilometres: 110000,
                    photo: [
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-1.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-1.jpg'),},
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-2.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-2.jpg'),},
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-3.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-3.jpg'),},
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-4.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-4.jpg'),},
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-5.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-5.jpg'),},
                        {img: require('@/assets/kia-sedona/ext/kia-sedona-ext-6.jpg'),img1: require('@/assets/kia-sedona/int/kia-sedona-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'Front wheel drive',
                        cylindersQuantity: '6 cylinders',
                        fuelConsumption: '13.2L per 100 km.',
                        topSpeed: 'Max speed 220 km/h',
                        horsePower: '276 HP',
                        acceleration: '0-100 in 11.0 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 6000 rpm',
                    },
                    description: 'The 2017 Kia Sedona is a worthy alternative to the top-rated minivans from Honda and Toyota. Besides the lower price and higher feature content, the Sedona scores points for its quick acceleration, quiet ride and carlike interior. The powerful engine does put a dent in fuel economy, and the cargo capacity is a bit smaller than that of rivals, but neither should be a deal breaker for savvy shoppers. Furthermore, its top safety score will give you some reassurance when transporting your most precious cargo, and Kia backs the car with the most generous warranty in the industry.',
                },
                // Audi Q7
                {
                    id: 10,
                    img1: require('@/assets/audi-q7/ext/audi-q7-ext-1.jpg'),
                    img2: require('@/assets/audi-q7/ext/audi-q7-ext-2.jpg'),
                    img3: require('@/assets/audi-q7/int/audi-q7-int-1.jpg'),
                    marke: 'Audi',
                    model: 'Q7',
                    price: 40500,
                    year: 2016,
                    bodyType: 'suv',
                    transmission: 'automatic',
                    kilometres: 93000,
                    photo: [
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-1.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-1.jpg'),},
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-2.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-2.jpg'),},
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-3.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-3.jpg'),},
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-4.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-4.jpg'),},
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-5.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-5.jpg'),},
                        {img: require('@/assets/audi-q7/ext/audi-q7-ext-6.jpg'),img1: require('@/assets/audi-q7/int/audi-q7-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '8 cylinders',
                        fuelConsumption: '7.2L per 100 km.',
                        topSpeed: 'Max speed 250 km/h',
                        horsePower: '429 HP',
                        acceleration: '0-100 in 4.9 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5200 rpm',
                    },
                    description: 'This engine produces a maximum power of 435 PS (429 bhp - 320 kW) at 3750-5000 rpm and a maximum torque of 900 Nm (663 lb.ft) at 1000-3250 rpm. The power is transmitted to the road by the all wheel drive (AWD) with a 8 speed Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Q7 II has Pneumatic.front suspension and Pneumatic.rear suspension.Stock tire sizes are 285 / 45 on 20 inch rims at the front, and 285 / 45 on 20 inch rims at the rear.For stopping power, the Q7 II SQ7 4.0 TDI 435HP Quattro 7-seats braking system includes Vented Discs at the front and Vented Discs at the rear. The Q7 II model is a TT car manufactured by Audi, with 5 doors and 7 seats, sold new from year 2016.',
                },
                // Continental GTC Speed'
                {
                    id: 11,
                    img1: require('@/assets/bentley-continental/ext/bentley-continental-ext-1.jpg'),
                    img2: require('@/assets/bentley-continental/ext/bentley-continental-ext-2.jpg'),
                    img3: require('@/assets/bentley-continental/int/bentley-continental-int-1.jpg'),
                    marke: 'Bentley',
                    model: 'Continental GTC Speed',
                    price: 48500,
                    year: 2010,
                    bodyType: 'convertiable',
                    transmission: 'automatic',
                    kilometres: 81000,
                    photo: [
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-1.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-1.jpg'),},
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-2.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-2.jpg'),},
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-3.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-3.jpg'),},
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-4.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-4.jpg'),},
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-5.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-5.jpg'),},
                        {img: require('@/assets/bentley-continental/ext/bentley-continental-ext-6.jpg'),img1: require('@/assets/bentley-continental/int/bentley-continental-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '12 cylinders',
                        fuelConsumption: '16.5L per 100 km.',
                        topSpeed: 'Max speed 318 km/h',
                        horsePower: '567 HP',
                        acceleration: '0-100 in 4.6 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 6000 rpm',
                    },
                    description: 'This engine produces a maximum power of 575 PS (567 bhp - 423 kW) at 6000 rpm and a maximum torque of 700 Nm (516 lb.ft) at 1700 rpm. The power is transmitted to the road by the all wheel drive (AWD) with a 6 speed Automatic gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Continental GT has Independent.Pneumatic.Anti - roll bar.front suspension and Independent.Pneumatic.Anti - roll bar.rear suspension.For stopping power, the Continental GT W12 braking system includes Vented Discs at the front and Vented Discs at the rear. The Continental GT model is a car manufactured by Bentley, with 2 doors and 4 seats, sold new from year 2010 until 2012, and available after that as a used car.',
                },
                // astonmartin db9
                {
                    id: 12,
                    img1: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-1.jpg'),
                    img2: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-2.jpg'),
                    img3: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-1.jpg'),
                    marke: 'Aston Martin',
                    model: 'DB9',
                    price: 50000,
                    year: 2004,
                    bodyType: 'coupe',
                    transmission: 'automatic',
                    kilometres: 49000,
                    photo: [
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-1.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-1.jpg'),},
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-2.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-2.jpg'),},
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-3.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-3.jpg'),},
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-4.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-4.jpg'),},
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-5.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-5.jpg'),},
                        {img: require('@/assets/astonmartin-db9/ext/astonmartin-db9-ext-6.jpg'),img1: require('@/assets/astonmartin-db9/int/astonmartin-db9-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '12 cylinders',
                        fuelConsumption: '16.6L per 100 km.',
                        topSpeed: 'Max speed 300 km/h',
                        horsePower: '449 HP',
                        acceleration: '0-100 in 4.9 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 6000 rpm',
                    },
                    description: 'This engine produces a maximum power of 455 PS (449 bhp - 335 kW) at 6000 rpm and a maximum torque of 570 Nm (420 lb.ft) at 5000 rpm. The power is transmitted to the road by the rear wheel drive (RWD) with a 6 speed Manual gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the DB9 has Coil springs.front suspension and Coil springs.rear suspension.Stock tire sizes are 235 / 40 on 19 inch rims at the front, and 275 / 35 on 19 inch rims at the rear.For stopping power, the DB9 Coupe braking system includes Vented Discs at the front and Vented Discs at the rear. The DB9 model is a Coupe car manufactured by Aston Martin, with 2 doors and 4 seats, sold new from year 2004 until 2008, and available after that as a used car.',
                },
                //Land Rover
                {
                    id: 13,
                    img1: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-1.jpg'),
                    img2: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-2.jpg'),
                    img3: require('@/assets/landrover-discovery/int/landrover-discovery-int-1.jpg'),
                    marke: 'Land Rover',
                    model: 'Discovery Sport Dynamic',
                    price: 20500,
                    year: 2016,
                    bodyType: 'suv',
                    transmission: 'automatic',
                    kilometres: 144000,
                     photo: [
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-1.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-1.jpg'),},
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-2.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-2.jpg'),},
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-3.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-3.jpg'),},
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-4.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-4.jpg'),},
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-5.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-5.jpg'),},
                        {img: require('@/assets/landrover-discovery/ext/landrover-discovery-ext-6.jpg'),img1: require('@/assets/landrover-discovery/int/landrover-discovery-int-6.jpg'),},
                    ],
                    detail: {
                        wheelDrive: 'All wheel drive',
                        cylindersQuantity: '4 cylinders',
                        fuelConsumption: '5.6L per 100 km.',
                        topSpeed: 'Max speed 180 km/h',
                        horsePower: '148 HP',
                        acceleration: '0-100 in 10.6 s.',
                        powerSteering: 'Power steering',
                        rpm: '1800 - 5000 rpm',
                    },
                    description: 'This engine produces a maximum power of 150 PS (148 bhp - 110 kW) at 3500 rpm and a maximum torque of 380 Nm (280 lb.ft) at 1750 rpm. The power is transmitted to the road by the front wheel drive (FWD) with a 6 speed Manual gearbox. On the topic of chassis details responsible for road holding, handling behavior and ride comfort, the Discovery Sport has McPherson struts.Coil springs.front suspension and Coil springs.rear suspension.Stock tire sizes are 235 / 60 on 18 inch rims at the front, and 235 / 60 on 18 inch rims at the rear.For stopping power, the Discovery Sport 2.0 eD4 150HP 4x2 HSE braking system includes Vented Discs at the front and Vented Discs at the rear. The Discovery Sport model is a TT car manufactured by Land Rover, with 5 doors and 5 seats, sold new from year 2016 until 2019, and available after that as a used car.',
                },
            ],
  },
    getters: {
        getProduct: state => id => {
            return _.find(state.cars, { id: id });
        },
        getMarke: state => marke => {
            return _.find(state.cars, { marke: marke });
        }
    },
  mutations: {
  },
  actions: {
  },
}